"""Four

Revision ID: 39c0a7982fb5
Revises: 4f634eb700df
Create Date: 2023-01-15 23:30:03.656279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c0a7982fb5'
down_revision = '4f634eb700df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
