"""10

Revision ID: 3d0bc7ef61df
Revises: fd1e4dfcc7d7
Create Date: 2023-01-22 17:02:33.465714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0bc7ef61df'
down_revision = 'fd1e4dfcc7d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu_id', sa.Integer(), nullable=True))
    op.drop_constraint('dish_submenu_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu_id'], ['id'])
    op.drop_column('dish', 'submenu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_submenu_fkey', 'dish', 'submenu', ['submenu'], ['id'])
    op.drop_column('dish', 'submenu_id')
    # ### end Alembic commands ###
