"""Three

Revision ID: 4f634eb700df
Revises: 52a286d5dfa1
Create Date: 2023-01-15 23:23:34.603245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f634eb700df'
down_revision = '52a286d5dfa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
