"""Five

Revision ID: b3be9d3802cb
Revises: 39c0a7982fb5
Create Date: 2023-01-15 23:35:11.822220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3be9d3802cb'
down_revision = '39c0a7982fb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
