"""11

Revision ID: c41bf3d366e7
Revises: 3d0bc7ef61df
Create Date: 2023-01-24 02:14:54.948302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41bf3d366e7'
down_revision = '3d0bc7ef61df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
