"""9

Revision ID: fd1e4dfcc7d7
Revises: 7e51ed7e999b
Create Date: 2023-01-20 21:58:00.334499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1e4dfcc7d7'
down_revision = '7e51ed7e999b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu_id', sa.Integer(), nullable=True))
    op.drop_constraint('dish_submenu_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu_id'], ['id'])
    op.drop_column('dish', 'submenu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_submenu_fkey', 'dish', 'submenu', ['submenu'], ['id'])
    op.drop_column('dish', 'submenu_id')
    # ### end Alembic commands ###
